from django.urls import path
from .views import (
    home,
    registroAgente,
    ticket_maker,
    obtener_agentes,
    inicio_atencion,
    atencion_agentes,
    atencion_agentes_registro,
    estados_reporte,
    numero_agente,
    numero_agente_registro,
    transferencia,
    ticketcontrol,
    adminside,
    cambiar_link_text,
    ticketsagente,
    datosagente,
    cambiar_imagen,
    casosagente,
    cambiar_cola,
    cambiar_visual,
    nuevoagente,
    colasatencion,
    configuracion,
    reproductor,
    estadosagente,
    ticketcontrolEncuesta,
    inicio_encuesta,
    registroEncuesta,
    metricas_guardado,
    digital_ticket_maker,

    crear_ticket_admision,
    crear_ticket_cajas,
    crear_ticket_cursolibre,
    crear_ticket_registro,
    crear_ticket_registro_tesis,
    crear_ticket_registro_convalidacion,
    crear_ticket_registro_congelamiento,
    crear_ticket_registro_suficiencia,
    crear_ticket_registro_graduacion,
    crear_ticket_registro_taller,
    crear_ticket_registro_retencion,
    crear_ticket_registro_apelacion,
    crear_ticket_registro_semirario,
    crear_ticket_registro_cartas,
    crear_ticket_registro_adecuaciones,
    crear_ticket_registro_actas,
    crear_ticket_registro_tcu,
    crear_ticket_registro_curso,
    crear_ticket_registro_examenes,
    crear_ticket_registro_matricula,

    digital_crear_ticket_admision,
    digital_crear_ticket_cajas,
    digital_crear_ticket_cursolibre,
    digital_crear_ticket_registro,
    digital_crear_ticket_registro_tesis,
    digital_crear_ticket_registro_convalidacion,
    digital_crear_ticket_registro_retiros,
    digital_crear_ticket_registro_suficiencia,
    digital_crear_ticket_registro_graduacion,
    digital_crear_ticket_registro_taller,
    digital_crear_ticket_registro_retencion,
    digital_crear_ticket_registro_apelacion,
    Logueo,
    RegistroAdmin,

    nuevodepartamento,
    modificardepartamento,
    eliminardepartamento,
    obtener_departamentos,

    nuevotramite,
    modificartramite,
    eliminartramite,

    ticket_maker_new,
    crear_ticket,
    cargar_tramites,

    obtener_todos_departamentos,
    eliminaragente,
    modificaragente,
)
from django.contrib.auth.views import LogoutView

# Create your models here.
urlpatterns = [
    path('', home, name='home'),
    path('login/', Logueo.as_view(), name='login'),
    path('registro-admin/', RegistroAdmin.as_view(), name='registro_admin'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('admin-side/', adminside, name='admin_side'),
    path('reproductor/', reproductor, name='reproductor'),
    path('cambiar-link-text/', cambiar_link_text, name='cambiar_link_text'),
    path('cambiar-imagen/', cambiar_imagen, name='cambiar_imagen'),
    path('cambiar-visual/', cambiar_visual, name='cambiar_visual'),
    path('nuevo-agente/', nuevoagente, name='nuevo_agente'),
    path('configuracion/', configuracion, name='configuracion'),
    path('cambiar-cola/', cambiar_cola, name='cambiar_cola'),
    path('colas-atencion/', colasatencion, name='colas_atencion'),
    path('estados_agente/', estadosagente, name='estados_agente'),
    path('casos-agente/', casosagente, name='casos_agente'),
    path('tickets-agente/', ticketsagente, name='tickets_agente'),
    path('datos-agente/', datosagente, name='datos_agente'),
    path('registro-agente/', registroAgente, name='registro_agente'),
    path('obtener-agentes/', obtener_agentes, name='obtener_agentes'),
    path('numero-agente/', numero_agente, name='numero_agente'),
    path('numero-agente-registro/', numero_agente_registro, name='numero_agente_registro'),
    path('ticket-maker/', ticket_maker, name='ticket_maker'),
    path('ticket-control/', ticketcontrol, name='ticket_control'),
    path('transferencia/', transferencia, name='transferencia'),
    path('atencion-agentes/', atencion_agentes, name='atencion_agentes'),
    path('atencion-agentes-registro/', atencion_agentes_registro, name='atencion_agentes_registro'),
    path('inicio-atencion/', inicio_atencion, name='inicio_atencion'),
    path('estados-reporte/', estados_reporte, name='estados_reporte'),

    path('ticket-control-encuesta/', ticketcontrolEncuesta, name='ticket_control_encuesta'),
    path('registro-encuesta/', registroEncuesta, name='registro_encuesta'),
    path('inicio-encuesta/', inicio_encuesta, name='inicio_encuesta'),
    path('metricas/', metricas_guardado, name='metricas'),

    path('crear-ticket-admision/', crear_ticket_admision, name='crear_ticket_admision'),
    path('crear-ticket-cajas/', crear_ticket_cajas, name='crear_ticket_cajas'),
    path('crear-ticket-cursolibre/', crear_ticket_cursolibre, name='crear_ticket_cursolibre'),
    path('crear-ticket-registro/', crear_ticket_registro, name='crear_ticket_registro'),
    path('crear-ticket-registro-tesis/', crear_ticket_registro_tesis, name='crear_ticket_registro_tesis'),
    path('crear-ticket-registro-convalidacion/', crear_ticket_registro_convalidacion, name='crear_ticket_registro_convalidacion'),
    path('crear-ticket-registro-congelamiento/', crear_ticket_registro_congelamiento, name='crear_ticket_registro_congelamiento'),
    path('crear-ticket-registro-suficiencia/', crear_ticket_registro_suficiencia, name='crear_ticket_registro_suficiencia'),
    path('crear-ticket-registro-graduacion/', crear_ticket_registro_graduacion, name='crear_ticket_registro_graduacion'),
    path('crear-ticket-registro-taller/', crear_ticket_registro_taller, name='crear_ticket_registro_taller'),
    path('crear-ticket-registro-apelacion/', crear_ticket_registro_apelacion, name='crear_ticket_registro_apelacion'),
    path('crear-ticket-registro-retencion/', crear_ticket_registro_retencion, name='crear_ticket_registro_retencion'),
    path('crear-ticket-registro-seminario/', crear_ticket_registro_semirario, name='crear_ticket_registro_semirario'),
    path('crear-ticket-registro-cartas/', crear_ticket_registro_cartas, name='crear_ticket_registro_cartas'),
    path('crear-ticket-registro-adecuaciones/', crear_ticket_registro_adecuaciones, name='crear_ticket_registro_adecuaciones'),
    path('crear-ticket-registro-actas/', crear_ticket_registro_actas, name='crear_ticket_registro_actas'),
    path('crear-ticket-registro-tcu/', crear_ticket_registro_tcu, name='crear_ticket_registro_tcu'),
    path('crear-ticket-registro-curso/', crear_ticket_registro_curso, name='crear_ticket_registro_curso'),
    path('crear-ticket-registro-examenes/', crear_ticket_registro_examenes, name='crear_ticket_registro_examenes'),
    path('crear-ticket-registro-matricula/', crear_ticket_registro_matricula, name='crear_ticket_registro_matricula'),

    path('digital-ticket-maker/', digital_ticket_maker, name='digital_ticket_maker'),
    path('digital-crear-ticket-admision/', digital_crear_ticket_admision, name='digital_crear_ticket_admision'),
    path('digital-crear-ticket-cajas/', digital_crear_ticket_cajas, name='digital_crear_ticket_cajas'),
    path('digital-crear-ticket-cursolibre/', digital_crear_ticket_cursolibre, name='digital_crear_ticket_cursolibre'),
    path('digital-crear-ticket-registro/', digital_crear_ticket_registro, name='digital_crear_ticket_registro'),
    path('digital-crear-ticket-registro-tesis/', digital_crear_ticket_registro_tesis, name='digital_crear_ticket_registro_tesis'),
    path('digital-crear-ticket-registro-convalidacion/', digital_crear_ticket_registro_convalidacion, name='digital_crear_ticket_registro_convalidacion'),
    path('digital-crear-ticket-registro-retiros/', digital_crear_ticket_registro_retiros, name='digital_crear_ticket_registro_retiros'),
    path('digital-crear-ticket-registro-suficiencia/', digital_crear_ticket_registro_suficiencia, name='digital_crear_ticket_registro_suficiencia'),
    path('digital-crear-ticket-registro-graduacion/', digital_crear_ticket_registro_graduacion, name='digital_crear_ticket_registro_graduacion'),
    path('digital-crear-ticket-registro-taller/', digital_crear_ticket_registro_taller, name='digital_crear_ticket_registro_taller'),
    path('digital-crear-ticket-registro-apelacion/', digital_crear_ticket_registro_apelacion, name='digital_crear_ticket_registro_apelacion'),
    path('digital-crear-ticket-registro-retencion/', digital_crear_ticket_registro_retencion, name='digital_crear_ticket_registro_retencion'),


    path('nuevo-departamento/', nuevodepartamento, name='nuevo_departamento'),
    path('modificar-departamento/', modificardepartamento, name='modificar_departamento'),
    path('eliminar-departamento/', eliminardepartamento, name='eliminar_departamento'),
    path('obtener-departamentos/', obtener_departamentos, name='obtener_departamentos'),

    path('nuevo-tramite/', nuevotramite, name='nuevo_tramite'),
    path('modificar-tramite/', modificartramite, name='modificar_tramite'),
    path('eliminar-tramite/', eliminartramite, name='eliminar_tramite'),

    path('ticket-maker-new/', ticket_maker_new, name='ticket_maker_new'),
    path('crear-ticket/', crear_ticket, name='crear_ticket'),
    path('cargar-tramites/', cargar_tramites, name='cargar_tramites'),

    path('obtener-todos-departamentos/', obtener_todos_departamentos, name='obtener_todos_departamentos'),
    path('eliminar-agente/', eliminaragente, name='eliminar_agente'),
    path('modificar-agente/', modificaragente, name='modificar_agente'),
]