version: "3"

networks:
    mynetwork:
      driver: bridge

services:
  
  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Costa_Rica
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - TZ=America/Costa_Rica
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@uia.ac.cr"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "America/Costa_Rica"
    ports:
      - "80:80"
    depends_on:
      - db